//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viime.Portable.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Config() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Viime.Portable.Resources.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MediaServicesBaseUrl {
            get {
                return ResourceManager.GetString("MediaServicesBaseUrl", resourceCulture);
            }
        }
        
        public static string ActiveDirectoryBaseUrl {
            get {
                return ResourceManager.GetString("ActiveDirectoryBaseUrl", resourceCulture);
            }
        }
        
        public static string ActiveDirectoryTenantId {
            get {
                return ResourceManager.GetString("ActiveDirectoryTenantId", resourceCulture);
            }
        }
        
        public static string MediaServicesPrimaryKey {
            get {
                return ResourceManager.GetString("MediaServicesPrimaryKey", resourceCulture);
            }
        }
        
        public static string MediaServicesAuthority {
            get {
                return ResourceManager.GetString("MediaServicesAuthority", resourceCulture);
            }
        }
        
        public static string MediaServicesClientId {
            get {
                return ResourceManager.GetString("MediaServicesClientId", resourceCulture);
            }
        }
        
        public static string MediaServicesClientSecret {
            get {
                return ResourceManager.GetString("MediaServicesClientSecret", resourceCulture);
            }
        }
        
        public static string MediaServicesResourceUrl {
            get {
                return ResourceManager.GetString("MediaServicesResourceUrl", resourceCulture);
            }
        }
        
        public static string MediaServicesPolicy {
            get {
                return ResourceManager.GetString("MediaServicesPolicy", resourceCulture);
            }
        }
        
        public static string MediaServicesApiVersion {
            get {
                return ResourceManager.GetString("MediaServicesApiVersion", resourceCulture);
            }
        }
        
        public static string MediaServicesRtmpUrl {
            get {
                return ResourceManager.GetString("MediaServicesRtmpUrl", resourceCulture);
            }
        }
    }
}
